name: ðŸš€ VPS Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4  # Corrected shorthand

      - name: ðŸ“‚ Sync to VPS
        uses: pressidium/sftp-deploy@v1  # Corrected shorthand
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          local_dir: '.' 
          remote_dir: '/home/maxfine/public_html/tharitourtravel.com/'