name: ðŸš€ VPS Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync to VPS via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'root' # usually root or a specific panel user
          server: ${{ secrets.FTP_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './*'
          remote_path: '/home/maxfine/public_html/tharitourtravel.com/'
          args: '-o ConnectTimeout=5'